### ISSUE TITLE
Organization Admin Account Management

### ISSUE THREAD

**Issue by Kealii** [MikeJerrodTravis/the_pivot#13]
As a Logged In Business Admin,
when I visit the User Dashboard,
and I click Edit Profile,
then I should be able to edit my name, email, password,

**Comment by Unsafepond** [comment]
we don't want them to be able to edit their email do we?

**Comment by travishaby** [comment]
hmmmmm it seems like one should be able to change the email associated with your organization...would that cause problems elsewhere in our app?
